name: tf-lab01-apply

on: 
  workflow_dispatch:

jobs:
  
  tf-lab01-apply:
    name: tf-lab01-apply
    runs-on: ubuntu-latest
    env: 
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID:  ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY:  ${{secrets.AWS_SECRET_ACCESS_KEY}}    

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install AWS cli
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update

    - name: Install Terraform
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install terraform

    - name: Terraform Init
      run: |
        cd lab01/
        terraform init -backend-config backend.tfvars   

    - name: Terraform Plan
      run: |
        cd lab01/
        terraform plan -var-file terraform.tfvars -out terraform.tfplan

    - name: Terraform Apply
      run: |
        cd lab01/
        terraform apply terraform.tfplan